### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [DemevengDerrick/odkconnector#1]
Please change the plugin homepage link to point to this repo rather than your personal website

**Comment by NyakudyaA** [comment]
ping @DemevengDerrick

**Comment by DemevengDerrick** [comment]
> ping @DemevengDerrick

Thanks for this review @NyakudyaA. I have published an update that includes the page to the plugin (https://demevengderrick.gitbook.io/odkconnector/).

Please let me know if you have some additional comments.
